import 'dotenv/config';
import { neon } from '@neondatabase/serverless';
import { drizzle } from 'drizzle-orm/neon-http';
import { equipment } from '../src/db/schema';
import { sql } from 'drizzle-orm';

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) throw new Error('DATABASE_URL is required');

const client = neon(DATABASE_URL);
const db = drizzle(client);

const listings = [
  // ══════════════ EXCAVATORS ══════════════
  {
    slug: 'caterpillar-330gc-2023-uae',
    brand: 'Caterpillar',
    model: '330 GC',
    category: 'Excavators',
    categorySlug: 'excavators',
    year: 2023,
    hours: 1240,
    condition: 'Used',
    price: '185000.00',
    currency: 'USD',
    location: 'Dubai, UAE',
    country: 'UAE',
    sellerName: 'Al Bahar Equipment',
    sellerType: 'Dealer',
    sellerLocation: 'Dubai',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1580901368919-7738efb0f228?w=800&q=80'],
    description: 'Caterpillar 330 GC hydraulic excavator in excellent working condition. Low hours, full service history available. Ideal for road construction, earthmoving, and general excavation projects in the Middle East.',
    features: ['GPS Grade Control Ready', 'Climate-Controlled Cab', 'Auto Idle Shutdown', 'Rear Camera', 'Quick Coupler'],
    specifications: { operatingWeight: '30,900 kg', netPower: '204 hp', maxDigDepth: '7.13 m', bucketCapacity: '1.54 m³' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: true,
  },
  {
    slug: 'komatsu-pc210lc-11-2022-usa',
    brand: 'Komatsu',
    model: 'PC210LC-11',
    category: 'Excavators',
    categorySlug: 'excavators',
    year: 2022,
    hours: 3200,
    condition: 'Used',
    price: '142000.00',
    currency: 'USD',
    location: 'Houston, TX',
    country: 'USA',
    sellerName: 'Lone Star Heavy Equipment',
    sellerType: 'Dealer',
    sellerLocation: 'Houston, TX',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1621922688758-8d11f4c02082?w=800&q=80'],
    description: 'Komatsu PC210LC-11 with KOMTRAX telematics system. Well-maintained fleet unit, perfect for utility and pipeline work.',
    features: ['KOMTRAX Telematics', 'Pattern Changer', 'Proportional Controls', 'LED Work Lights'],
    specifications: { operatingWeight: '22,580 kg', netPower: '159 hp', maxDigDepth: '6.71 m', bucketCapacity: '1.06 m³' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: true,
  },
  {
    slug: 'volvo-ec480el-2024-germany',
    brand: 'Volvo',
    model: 'EC480EL',
    category: 'Excavators',
    categorySlug: 'excavators',
    year: 2024,
    hours: 420,
    condition: 'Used',
    price: '295000.00',
    currency: 'USD',
    location: 'Munich, Germany',
    country: 'Germany',
    sellerName: 'Swecon Baumaschinen',
    sellerType: 'Dealer',
    sellerLocation: 'Munich',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1597753781757-fbd8b9793c56?w=800&q=80'],
    description: 'Nearly new Volvo EC480EL long-reach excavator. Premium specification with Volvo Smart View camera system. Only 420 hours.',
    features: ['Volvo Smart View 360°', 'Electro-Hydraulic Controls', 'Hill Assist', 'Boom Float', 'Auto Climate'],
    specifications: { operatingWeight: '47,600 kg', netPower: '345 hp', maxDigDepth: '8.16 m', bucketCapacity: '2.41 m³' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: true,
  },
  {
    slug: 'sany-sy215c-2023-india',
    brand: 'SANY',
    model: 'SY215C',
    category: 'Excavators',
    categorySlug: 'excavators',
    year: 2023,
    hours: 1800,
    condition: 'Used',
    price: '98000.00',
    currency: 'USD',
    location: 'Mumbai, India',
    country: 'India',
    sellerName: 'SANY India Pvt Ltd',
    sellerType: 'Manufacturer',
    sellerLocation: 'Mumbai',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1599059813005-11265ba4b4ce?w=800&q=80'],
    description: 'SANY SY215C mid-size excavator. Exceptional value with low operating costs. Ideal for infrastructure projects.',
    features: ['DOMCS System', 'Energy Saving Mode', 'Auto Warm-Up', 'Centralized Lubrication'],
    specifications: { operatingWeight: '21,700 kg', netPower: '150 hp', maxDigDepth: '6.52 m', bucketCapacity: '1.0 m³' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: false,
  },
  {
    slug: 'hitachi-zx350lc-7-2023-australia',
    brand: 'Hitachi',
    model: 'ZX350LC-7',
    category: 'Excavators',
    categorySlug: 'excavators',
    year: 2023,
    hours: 2100,
    condition: 'Used',
    price: '228000.00',
    currency: 'USD',
    location: 'Perth, Australia',
    country: 'Australia',
    sellerName: 'Hitachi Construction Machinery Australia',
    sellerType: 'Dealer',
    sellerLocation: 'Perth',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1504307651254-35680f356f27?w=800&q=80'],
    description: 'Hitachi ZX350LC-7 with TRIAS III hydraulic system. Mining-spec machine, ready for demanding Australian conditions.',
    features: ['TRIAS III Hydraulics', 'ConSite Health Monitoring', 'AERIAL ANGLE Camera', 'Auto Power Boost'],
    specifications: { operatingWeight: '35,200 kg', netPower: '270 hp', maxDigDepth: '7.42 m', bucketCapacity: '1.5 m³' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: false,
  },
  // ══════════════ BULLDOZERS ══════════════
  {
    slug: 'caterpillar-d6t-xl-2022-usa',
    brand: 'Caterpillar',
    model: 'D6T XL',
    category: 'Bulldozers',
    categorySlug: 'bulldozers',
    year: 2022,
    hours: 4800,
    condition: 'Used',
    price: '245000.00',
    currency: 'USD',
    location: 'Atlanta, GA',
    country: 'USA',
    sellerName: 'Yancey Bros. Co.',
    sellerType: 'Dealer',
    sellerLocation: 'Atlanta, GA',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1513828583688-c52646db42da?w=800&q=80'],
    description: 'Cat D6T XL with power-angle-tilt blade. Differential steering for superior maneuverability. Full Cat Certified Rebuild eligible.',
    features: ['VPAT Blade', 'Differential Steering', 'Stable Blade', 'AccuGrade GPS Ready', 'Auto Ripper'],
    specifications: { operatingWeight: '23,860 kg', netPower: '215 hp', bladeCapacity: '4.29 m³', groundPressure: '47.7 kPa' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: true,
  },
  {
    slug: 'komatsu-d65px-18-2023-japan',
    brand: 'Komatsu',
    model: 'D65PX-18',
    category: 'Bulldozers',
    categorySlug: 'bulldozers',
    year: 2023,
    hours: 1500,
    condition: 'Used',
    price: '275000.00',
    currency: 'USD',
    location: 'Osaka, Japan',
    country: 'Japan',
    sellerName: 'Komatsu Japan Direct',
    sellerType: 'Manufacturer',
    sellerLocation: 'Osaka',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1541888087625-0547078e6fa3?w=800&q=80'],
    description: 'Komatsu D65PX-18 low-ground-pressure dozer. Perfect for soft soil conditions and wetland construction.',
    features: ['Sigma Blade', 'Palm Command Joystick', 'KOMTRAX Plus', 'Lock-Up Torque Converter'],
    specifications: { operatingWeight: '22,540 kg', netPower: '217 hp', bladeCapacity: '5.61 m³', groundPressure: '37.3 kPa' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: false,
  },
  // ══════════════ CRANES ══════════════
  {
    slug: 'liebherr-ltm1100-5-2-2022-germany',
    brand: 'Liebherr',
    model: 'LTM 1100-5.2',
    category: 'Cranes',
    categorySlug: 'cranes',
    year: 2022,
    hours: 3200,
    condition: 'Used',
    price: '680000.00',
    currency: 'USD',
    location: 'Hamburg, Germany',
    country: 'Germany',
    sellerName: 'Liebherr-Werk Ehingen',
    sellerType: 'Manufacturer',
    sellerLocation: 'Ehingen',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1504307651254-35680f356f27?w=800&q=80'],
    description: 'Liebherr LTM 1100-5.2 all-terrain crane. 100-ton lifting capacity. VarioBase Plus for optimized outrigger setup.',
    features: ['VarioBase Plus', 'Telematic System', '50m Telescopic Boom', 'ECOmode', 'LICCON2 Control System'],
    specifications: { maxCapacity: '100 tonnes', maxBoomLength: '50 m', maxHeight: '70 m', counterweight: '14 tonnes' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: true,
  },
  {
    slug: 'tadano-gr-1000xl-4-2023-usa',
    brand: 'Tadano',
    model: 'GR-1000XL-4',
    category: 'Cranes',
    categorySlug: 'cranes',
    year: 2023,
    hours: 800,
    condition: 'Used',
    price: '520000.00',
    currency: 'USD',
    location: 'Chicago, IL',
    country: 'USA',
    sellerName: 'Maxim Crane Works',
    sellerType: 'Dealer',
    sellerLocation: 'Chicago, IL',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=800&q=80'],
    description: 'Tadano GR-1000XL-4 rough terrain crane. 100-ton capacity with Tadano Smart Chart system for automated load calculations.',
    features: ['Smart Chart System', 'Hello-Net Telematics', 'Positive Boom Controls', 'AML-C Load Indicator'],
    specifications: { maxCapacity: '100 US tons', mainBoom: '43.2 m', maxTipHeight: '65 m', travelSpeed: '35 km/h' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: false,
  },
  // ══════════════ WHEEL LOADERS ══════════════
  {
    slug: 'caterpillar-966m-xe-2023-canada',
    brand: 'Caterpillar',
    model: '966M XE',
    category: 'Wheel Loaders',
    categorySlug: 'wheel-loaders',
    year: 2023,
    hours: 2400,
    condition: 'Used',
    price: '310000.00',
    currency: 'USD',
    location: 'Calgary, Canada',
    country: 'Canada',
    sellerName: 'Finning International',
    sellerType: 'Dealer',
    sellerLocation: 'Calgary',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1599059813005-11265ba4b4ce?w=800&q=80'],
    description: 'Cat 966M XE with advanced continuously variable transmission (CVT). 25% more fuel efficient than standard models.',
    features: ['CVT Transmission', 'Payload Estimation', 'Auto Dig Assist', 'Fusion Quick Coupler', 'Rear Object Detection'],
    specifications: { operatingWeight: '24,494 kg', netPower: '275 hp', bucketCapacity: '4.0 m³', breakoutForce: '201 kN' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: true,
  },
  {
    slug: 'volvo-l120h-2022-uk',
    brand: 'Volvo',
    model: 'L120H',
    category: 'Wheel Loaders',
    categorySlug: 'wheel-loaders',
    year: 2022,
    hours: 3800,
    condition: 'Used',
    price: '178000.00',
    currency: 'USD',
    location: 'Birmingham, UK',
    country: 'UK',
    sellerName: 'SMT GB',
    sellerType: 'Dealer',
    sellerLocation: 'Birmingham',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1580901368919-7738efb0f228?w=800&q=80'],
    description: 'Volvo L120H with OptiShift and Reverse By Braking technology. Quarry specification with rock bucket.',
    features: ['OptiShift CVT', 'Load Assist', 'Volvo Co-Pilot', 'Boom Suspension', 'Auto Engine Shutdown'],
    specifications: { operatingWeight: '19,600 kg', netPower: '204 hp', bucketCapacity: '3.4 m³', breakoutForce: '172 kN' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: false,
  },
  // ══════════════ DUMP TRUCKS ══════════════
  {
    slug: 'caterpillar-745-2023-usa',
    brand: 'Caterpillar',
    model: '745',
    category: 'Dump Trucks',
    categorySlug: 'dump-trucks',
    year: 2023,
    hours: 3100,
    condition: 'Used',
    price: '425000.00',
    currency: 'USD',
    location: 'Denver, CO',
    country: 'USA',
    sellerName: 'Wagner Equipment Co.',
    sellerType: 'Dealer',
    sellerLocation: 'Denver, CO',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1621922688758-8d11f4c02082?w=800&q=80'],
    description: 'Cat 745 articulated dump truck. 45.2-tonne payload capacity. Terrain-based speed control for maximum safety.',
    features: ['Terrain Speed Control', 'Stability Assist', 'Cat Connect Payload', 'Auto Retarder', 'Traction Control'],
    specifications: { payloadCapacity: '45.2 tonnes', heapedCapacity: '26.1 m³', netPower: '504 hp', maxSpeed: '57 km/h' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: true,
  },
  {
    slug: 'volvo-a30g-2022-sweden',
    brand: 'Volvo',
    model: 'A30G',
    category: 'Dump Trucks',
    categorySlug: 'dump-trucks',
    year: 2022,
    hours: 4200,
    condition: 'Used',
    price: '285000.00',
    currency: 'USD',
    location: 'Stockholm, Sweden',
    country: 'Sweden',
    sellerName: 'Swecon Anläggningsmaskiner',
    sellerType: 'Dealer',
    sellerLocation: 'Stockholm',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1504307651254-35680f356f27?w=800&q=80'],
    description: 'Volvo A30G articulated hauler. 28-tonne payload with full suspension and on-board weighing system.',
    features: ['Full Suspension', 'On-Board Weighing', 'Volvo Active Steering', 'Hill Assist', 'MATRIS Monitoring'],
    specifications: { payloadCapacity: '28 tonnes', heapedCapacity: '17.5 m³', netPower: '370 hp', maxSpeed: '53 km/h' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: false,
  },
  // ══════════════ BACKHOE LOADERS ══════════════
  {
    slug: 'jcb-3cx-2024-uk',
    brand: 'JCB',
    model: '3CX',
    category: 'Backhoe Loaders',
    categorySlug: 'backhoe-loaders',
    year: 2024,
    hours: 320,
    condition: 'New',
    price: '92000.00',
    currency: 'USD',
    location: 'London, UK',
    country: 'UK',
    sellerName: 'Gunn JCB',
    sellerType: 'Dealer',
    sellerLocation: 'London',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1597753781757-fbd8b9793c56?w=800&q=80'],
    description: 'Brand new JCB 3CX backhoe loader. The world\'s best-selling backhoe with JCB EcoMAX engine.',
    features: ['EcoMAX Engine', 'Smooth Ride System', 'Auto Return Dig', 'Powerslide Transmission', 'LiveLink Telematics'],
    specifications: { operatingWeight: '8,040 kg', netPower: '74 kW', maxDigDepth: '5.97 m', loaderCapacity: '1.0 m³' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: true,
  },
  {
    slug: 'case-580sv-2023-brazil',
    brand: 'CASE',
    model: '580SV',
    category: 'Backhoe Loaders',
    categorySlug: 'backhoe-loaders',
    year: 2023,
    hours: 1100,
    condition: 'Used',
    price: '68000.00',
    currency: 'USD',
    location: 'São Paulo, Brazil',
    country: 'Brazil',
    sellerName: 'Case IH Brasil',
    sellerType: 'Dealer',
    sellerLocation: 'São Paulo',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1580901368919-7738efb0f228?w=800&q=80'],
    description: 'CASE 580SV Super V backhoe. ProControl electronic auxiliary hydraulics for precise attachment control.',
    features: ['ProControl Hydraulics', 'PowerBoost', 'Auto Ride Control', 'Extendable Dipper'],
    specifications: { operatingWeight: '8,300 kg', netPower: '69 kW', maxDigDepth: '5.60 m', loaderCapacity: '1.15 m³' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: false,
  },
  // ══════════════ SKID STEERS ══════════════
  {
    slug: 'bobcat-s770-2024-usa',
    brand: 'Bobcat',
    model: 'S770',
    category: 'Skid Steers',
    categorySlug: 'skid-steers',
    year: 2024,
    hours: 180,
    condition: 'New',
    price: '72000.00',
    currency: 'USD',
    location: 'Minneapolis, MN',
    country: 'USA',
    sellerName: 'Bobcat of the Twin Cities',
    sellerType: 'Dealer',
    sellerLocation: 'Minneapolis, MN',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1621922688758-8d11f4c02082?w=800&q=80'],
    description: 'New Bobcat S770 large-frame skid steer. 3,350 lb rated operating capacity. Perfect for heavy landscaping and construction.',
    features: ['Bob-Tach Mounting', 'Selectable Joystick Controls', 'Deluxe Cab Package', '2-Speed Travel', 'Reversible Fan'],
    specifications: { ratedCapacity: '1,520 kg', operatingWeight: '4,536 kg', netPower: '92 hp', tippingLoad: '3,040 kg' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: false,
  },
  // ══════════════ MOTOR GRADERS ══════════════
  {
    slug: 'caterpillar-140m3-2022-south-africa',
    brand: 'Caterpillar',
    model: '140M3',
    category: 'Motor Graders',
    categorySlug: 'motor-graders',
    year: 2022,
    hours: 5200,
    condition: 'Used',
    price: '195000.00',
    currency: 'USD',
    location: 'Johannesburg, South Africa',
    country: 'South Africa',
    sellerName: 'Barloworld Equipment',
    sellerType: 'Dealer',
    sellerLocation: 'Johannesburg',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1513828583688-c52646db42da?w=800&q=80'],
    description: 'Cat 140M3 motor grader with AccuGrade GPS. Mine-specification machine built for African conditions.',
    features: ['AccuGrade GPS', 'All-Wheel Drive', 'Articulated Frame', 'Joystick Controls', 'Circle Drive Slip Clutch'],
    specifications: { bladeWidth: '4.27 m', netPower: '192 hp', operatingWeight: '17,800 kg', moldboardReach: '2.2 m' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: false,
  },
  {
    slug: 'john-deere-672gp-2023-usa',
    brand: 'John Deere',
    model: '672GP',
    category: 'Motor Graders',
    categorySlug: 'motor-graders',
    year: 2023,
    hours: 2800,
    condition: 'Used',
    price: '320000.00',
    currency: 'USD',
    location: 'Dallas, TX',
    country: 'USA',
    sellerName: 'John Deere Dealer',
    sellerType: 'Dealer',
    sellerLocation: 'Dallas, TX',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1599059813005-11265ba4b4ce?w=800&q=80'],
    description: 'John Deere 672GP production-class motor grader. SmartGrade technology with integrated GPS for precision grading.',
    features: ['SmartGrade GPS', 'GRADE Pro Cross Slope', 'F-Series Cab', 'Auto Articulation', 'e-Ramp Transmission'],
    specifications: { bladeWidth: '4.88 m', netPower: '265 hp', operatingWeight: '23,000 kg', moldboardReach: '2.6 m' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: true,
  },
  // ══════════════ TELEHANDLERS ══════════════
  {
    slug: 'jcb-540-200-2024-uae',
    brand: 'JCB',
    model: '540-200',
    category: 'Telehandlers',
    categorySlug: 'telehandlers',
    year: 2024,
    hours: 150,
    condition: 'New',
    price: '135000.00',
    currency: 'USD',
    location: 'Abu Dhabi, UAE',
    country: 'UAE',
    sellerName: 'Kanoo Machinery',
    sellerType: 'Dealer',
    sellerLocation: 'Abu Dhabi',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=800&q=80'],
    description: 'Brand new JCB 540-200 telehandler. 20-metre lift height, 4-tonne capacity. Designed for high-rise construction.',
    features: ['20m Lift Height', 'Smooth Ride', 'LiveLink Telematics', 'Auto Disconnect', 'Load Moment Indicator'],
    specifications: { maxCapacity: '4,000 kg', maxLiftHeight: '19.7 m', netPower: '130 hp', maxForwardReach: '16.3 m' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: false,
  },
  // ══════════════ COMPACTORS ══════════════
  {
    slug: 'hamm-h13i-2023-germany',
    brand: 'HAMM',
    model: 'H 13i',
    category: 'Compactors',
    categorySlug: 'compactors',
    year: 2023,
    hours: 900,
    condition: 'Used',
    price: '165000.00',
    currency: 'USD',
    location: 'Frankfurt, Germany',
    country: 'Germany',
    sellerName: 'Wirtgen Group',
    sellerType: 'Manufacturer',
    sellerLocation: 'Frankfurt',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1513828583688-c52646db42da?w=800&q=80'],
    description: 'HAMM H 13i compactor with oscillation technology. 13-tonne operating weight for highway and airport runway construction.',
    features: ['Oscillation Drum', 'HCQ Navigator', 'Smart Compact', 'Three-Point Articulation', 'Ergonomic Cab'],
    specifications: { operatingWeight: '13,100 kg', drumWidth: '2,140 mm', centrifugalForce: '263/175 kN', amplitude: '1.97/0.89 mm' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: false,
  },
  // ══════════════ FORKLIFTS ══════════════
  {
    slug: 'toyota-8fgu25-2024-japan',
    brand: 'Toyota',
    model: '8FGU25',
    category: 'Forklifts',
    categorySlug: 'forklifts',
    year: 2024,
    hours: 50,
    condition: 'New',
    price: '32000.00',
    currency: 'USD',
    location: 'Tokyo, Japan',
    country: 'Japan',
    sellerName: 'Toyota Material Handling',
    sellerType: 'Manufacturer',
    sellerLocation: 'Tokyo',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1597753781757-fbd8b9793c56?w=800&q=80'],
    description: 'Toyota 8FGU25 pneumatic tire forklift. 5,000 lb capacity. Industry-leading reliability with System of Active Stability.',
    features: ['SAS System', 'OAT Coolant', 'Auto Parking Brake', 'Multi-Function Display', 'Eco/Power Modes'],
    specifications: { capacity: '2,500 kg', liftHeight: '3,000 mm', forkLength: '1,070 mm', turnRadius: '2,180 mm' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: false,
  },
  {
    slug: 'hyster-h5-0ft-2023-usa',
    brand: 'Hyster',
    model: 'H5.0FT',
    category: 'Forklifts',
    categorySlug: 'forklifts',
    year: 2023,
    hours: 600,
    condition: 'Used',
    price: '28000.00',
    currency: 'USD',
    location: 'Los Angeles, CA',
    country: 'USA',
    sellerName: 'Pacific Coast Forklifts',
    sellerType: 'Dealer',
    sellerLocation: 'Los Angeles, CA',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1580901368919-7738efb0f228?w=800&q=80'],
    description: 'Hyster H5.0FT with integrated Hyster Tracker telematics. Excellent for high-throughput warehouse operations.',
    features: ['Hyster Tracker', 'Dual Drive Axle', 'Full Free Lift Mast', 'Integrated Side Shift', 'LED Lights'],
    specifications: { capacity: '5,000 kg', liftHeight: '6,000 mm', forkLength: '1,200 mm', travelSpeed: '23 km/h' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: false,
  },
  // ══════════════ MORE EXCAVATORS (variety) ══════════════
  {
    slug: 'kobelco-sk500lc-11-2023-usa',
    brand: 'Kobelco',
    model: 'SK500LC-11',
    category: 'Excavators',
    categorySlug: 'excavators',
    year: 2023,
    hours: 2800,
    condition: 'Used',
    price: '365000.00',
    currency: 'USD',
    location: 'Phoenix, AZ',
    country: 'USA',
    sellerName: 'Road Machinery & Supplies',
    sellerType: 'Dealer',
    sellerLocation: 'Phoenix, AZ',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1504307651254-35680f356f27?w=800&q=80'],
    description: 'Kobelco SK500LC-11 mass excavator. 50-tonne class with iNDr cooling system for reduced noise and improved performance.',
    features: ['iNDr Cooling', 'Independent Travel', 'KOBELCO NEXT Telematics', 'Boom Suspension', 'Power Boost'],
    specifications: { operatingWeight: '50,600 kg', netPower: '345 hp', maxDigDepth: '7.94 m', bucketCapacity: '2.75 m³' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: false,
  },
  {
    slug: 'doosan-dx225lc-7-2024-south-korea',
    brand: 'Doosan',
    model: 'DX225LC-7',
    category: 'Excavators',
    categorySlug: 'excavators',
    year: 2024,
    hours: 350,
    condition: 'New',
    price: '155000.00',
    currency: 'USD',
    location: 'Seoul, South Korea',
    country: 'South Korea',
    sellerName: 'HD Hyundai Infracore',
    sellerType: 'Manufacturer',
    sellerLocation: 'Seoul',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1621922688758-8d11f4c02082?w=800&q=80'],
    description: 'Latest Doosan DX225LC-7 with D-ECOPOWER technology. 8% more fuel efficient than previous models.',
    features: ['D-ECOPOWER', 'DoosanCONNECT Telematics', 'Smart Power Control', 'Automatic Swing Parking Brake', 'Wide LED Lights'],
    specifications: { operatingWeight: '22,900 kg', netPower: '171 hp', maxDigDepth: '6.65 m', bucketCapacity: '1.08 m³' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: true,
  },
  // ══════════════ ADDITIONAL MIX ══════════════
  {
    slug: 'xcmg-xc948-2023-china',
    brand: 'XCMG',
    model: 'XC948',
    category: 'Wheel Loaders',
    categorySlug: 'wheel-loaders',
    year: 2023,
    hours: 1200,
    condition: 'Used',
    price: '75000.00',
    currency: 'USD',
    location: 'Shanghai, China',
    country: 'China',
    sellerName: 'XCMG Global',
    sellerType: 'Manufacturer',
    sellerLocation: 'Shanghai',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1599059813005-11265ba4b4ce?w=800&q=80'],
    description: 'XCMG XC948 wheel loader. Competitive pricing with world-class components including ZF transmission and Dana axles.',
    features: ['ZF Transmission', 'Dana Axles', 'Intelligent Weighing', 'Centralized Lubrication', 'ROPS/FOPS Cab'],
    specifications: { operatingWeight: '17,200 kg', netPower: '175 hp', bucketCapacity: '2.5 m³', breakoutForce: '155 kN' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: false,
  },
  {
    slug: 'hyundai-hx220al-2024-south-korea',
    brand: 'Hyundai',
    model: 'HX220AL',
    category: 'Excavators',
    categorySlug: 'excavators',
    year: 2024,
    hours: 200,
    condition: 'New',
    price: '168000.00',
    currency: 'USD',
    location: 'Busan, South Korea',
    country: 'South Korea',
    sellerName: 'HD Hyundai Construction Equipment',
    sellerType: 'Manufacturer',
    sellerLocation: 'Busan',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1597753781757-fbd8b9793c56?w=800&q=80'],
    description: 'New Hyundai HX220AL excavator with EPFC hydraulic system. Industry-leading fuel efficiency in its class.',
    features: ['EPFC Hydraulics', 'Hi-Mate Remote Management', 'Virtual Bleed-Off', 'Boom Float', 'Premium Cab'],
    specifications: { operatingWeight: '22,400 kg', netPower: '180 hp', maxDigDepth: '6.67 m', bucketCapacity: '1.14 m³' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: false,
  },
  {
    slug: 'caterpillar-950gc-2023-nigeria',
    brand: 'Caterpillar',
    model: '950 GC',
    category: 'Wheel Loaders',
    categorySlug: 'wheel-loaders',
    year: 2023,
    hours: 1800,
    condition: 'Used',
    price: '198000.00',
    currency: 'USD',
    location: 'Lagos, Nigeria',
    country: 'Nigeria',
    sellerName: 'Mantrac Nigeria',
    sellerType: 'Dealer',
    sellerLocation: 'Lagos',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1513828583688-c52646db42da?w=800&q=80'],
    description: 'Cat 950 GC wheel loader built for demanding conditions in West Africa. Simplified maintenance with ground-level service points.',
    features: ['Ground-Level Service', 'Ride Control', 'Lock-Up Clutch Torque Converter', 'Reversible Fan', 'Payload Weighing'],
    specifications: { operatingWeight: '18,700 kg', netPower: '216 hp', bucketCapacity: '3.1 m³', breakoutForce: '170 kN' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: false,
  },
  {
    slug: 'manitou-mt1840-2024-france',
    brand: 'Manitou',
    model: 'MT 1840',
    category: 'Telehandlers',
    categorySlug: 'telehandlers',
    year: 2024,
    hours: 100,
    condition: 'New',
    price: '112000.00',
    currency: 'USD',
    location: 'Paris, France',
    country: 'France',
    sellerName: 'Manitou Group',
    sellerType: 'Manufacturer',
    sellerLocation: 'Paris',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1590523277543-a94d2e4eb00b?w=800&q=80'],
    description: 'Manitou MT 1840 telehandler. 18-metre lift height with 4-tonne capacity. JSM joystick for intuitive single-hand operation.',
    features: ['JSM Joystick', 'M-Vario Plus Transmission', 'EasyManager Telematics', 'Auto Disconnect', 'Load Moment Indicator'],
    specifications: { maxCapacity: '4,000 kg', maxLiftHeight: '17.5 m', netPower: '136 hp', maxForwardReach: '13.5 m' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: false,
  },
  {
    slug: 'komatsu-wa380-8-2023-chile',
    brand: 'Komatsu',
    model: 'WA380-8',
    category: 'Wheel Loaders',
    categorySlug: 'wheel-loaders',
    year: 2023,
    hours: 2900,
    condition: 'Used',
    price: '215000.00',
    currency: 'USD',
    location: 'Santiago, Chile',
    country: 'Chile',
    sellerName: 'Komatsu Cummins Chile',
    sellerType: 'Dealer',
    sellerLocation: 'Santiago',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1580901368919-7738efb0f228?w=800&q=80'],
    description: 'Komatsu WA380-8 wheel loader configured for mining aggregate operations in South America. Full KOMTRAX fleet management.',
    features: ['KOMTRAX Plus', 'Modulated Clutch', 'HST Auto Decel', 'Variable Traction Control', 'Auto-Dig'],
    specifications: { operatingWeight: '19,700 kg', netPower: '197 hp', bucketCapacity: '3.6 m³', breakoutForce: '174 kN' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: false,
  },
  // ══════════════ GENERATORS ══════════════
  {
    slug: 'caterpillar-c18-generator-2024-uae',
    brand: 'Caterpillar',
    model: 'C18 660kVA',
    category: 'Generators',
    categorySlug: 'generators',
    year: 2024,
    hours: 120,
    condition: 'New',
    price: '85000.00',
    currency: 'USD',
    location: 'Riyadh, Saudi Arabia',
    country: 'Saudi Arabia',
    sellerName: 'Zahid Tractor',
    sellerType: 'Dealer',
    sellerLocation: 'Riyadh',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1504307651254-35680f356f27?w=800&q=80'],
    description: 'Cat C18 diesel generator set. 660 kVA prime power. Sound-attenuated enclosure rated for extreme desert heat.',
    features: ['Sound Attenuated Enclosure', 'Auto Transfer Switch', 'EMCP 4.4 Controller', 'Block Heater', 'Fuel Priming Pump'],
    specifications: { primeRating: '660 kVA', frequency: '50 Hz', voltage: '380-415V', fuelCapacity: '1,000 L' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: false,
  },
  // ══════════════ MINI EXCAVATORS ══════════════
  {
    slug: 'kubota-kx080-4-2024-usa',
    brand: 'Kubota',
    model: 'KX080-4',
    category: 'Excavators',
    categorySlug: 'excavators',
    year: 2024,
    hours: 75,
    condition: 'New',
    price: '89000.00',
    currency: 'USD',
    location: 'Orlando, FL',
    country: 'USA',
    sellerName: 'Kubota Tractor Corp.',
    sellerType: 'Dealer',
    sellerLocation: 'Orlando, FL',
    sellerVerified: true,
    images: ['https://images.unsplash.com/photo-1621922688758-8d11f4c02082?w=800&q=80'],
    description: 'New Kubota KX080-4 compact excavator. 8-tonne class with conventional tail swing. Ideal for urban construction.',
    features: ['Auto-Idle', 'Proportional Auxiliary', 'Eco Mode', 'ROPS/FOPS Cab', 'Dozer Blade'],
    specifications: { operatingWeight: '8,580 kg', netPower: '65.7 hp', maxDigDepth: '4.61 m', bucketCapacity: '0.28 m³' },
    affiliateUrl: null,
    affiliateNetwork: null,
    status: 'ACTIVE',
    featured: false,
  },
];

async function seed() {
  console.log('🚜 Starting IRONMARKET equipment seed...');
  console.log(`📦 ${listings.length} listings to insert`);

  // Clear existing data
  await db.delete(equipment);
  console.log('🗑️  Cleared existing equipment');

  // Insert all listings
  for (const listing of listings) {
    await db.insert(equipment).values(listing as any);
    console.log(`  ✅ ${listing.brand} ${listing.model} (${listing.location})`);
  }

  console.log(`\n🎉 Successfully seeded ${listings.length} equipment listings!`);
  console.log('Categories covered:');
  const cats = [...new Set(listings.map(l => l.category))];
  cats.forEach(c => {
    const count = listings.filter(l => l.category === c).length;
    console.log(`  📁 ${c}: ${count} listings`);
  });

  process.exit(0);
}

seed().catch((err) => {
  console.error('❌ Seed failed:', err);
  process.exit(1);
});
